# DingTalk Channel Plugin Makefile
PLUGIN_TYPE = channels
PLUGIN_NAME = dingtalk_channel
PLUGIN_SRC = dingtalk_channel.c dingtalk_ws.c
PRIMAGEN_ROOT = ../../..
include $(PRIMAGEN_ROOT)/plugins/common.mk
