PLUGIN_TYPE = tools
PLUGIN_NAME = mcp_tools
PLUGIN_SRC = mcp_plugin.c mcp.c mcp_tools.c transport_stdio.c transport_websocket.c transport_sse.c transport_streamable_http.c
PRIMAGEN_ROOT = ../../..
include $(PRIMAGEN_ROOT)/plugins/common.mk
